### ISSUE TITLE
Add a document with details about how piece table works

### ISSUE THREAD

**Issue by prasenjit** [prasenjit/PieceTable#1]

**Comment by Himanshu-Modi** [comment]
could you elaborate it more.
I could understand that we needed to create a readme in this.

**Comment by Hinal-Srivastava** [comment]
Hi!
I can take this up

**Comment by prasenjit** [comment]
@Himanshu-Modi I need a document in the project explaining how piece table works and where it is used.

**Comment by prasenjit** [comment]
@Himanshu-Modi @Hinal-Srivastava You both can submit a PR and then I will merge the better document.
